version: "3.9"
services:
  postgresql:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: 1234
    ports:
      - "25432:5432"
  api:
    build:
      context: ./backend/app-api
      dockerfile: Dockerfile
    # env_file:
    #   - "./backend/app-api/.env"
    environment:
      DB_HOST: host.docker.internal
    ports:
      - "8080:80"
    depends_on:
      - postgresql
  frontend:
    build:
      context: ./frontend/vue-app
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api